In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('results__landmine_mini.csv', index_col=0)
df

                     accuracy  f1_macro  recall_macro
model
ind_nn_8                0.932  0.535884      0.530107
common_nn_8             0.936  0.505652      0.512500
cvx_nn_8                0.930  0.504038      0.511083
cvx-trainable_nn_8      0.932  0.507350      0.512135
ind_nn_16               0.930  0.532567      0.529055
common_nn_16            0.936  0.512002      0.516667
cvx_nn_16               0.934  0.511456      0.515580
cvx-trainable_nn_16     0.934  0.532864      0.531206
ind_nn_32               0.930  0.529012      0.524911
common_nn_32            0.936  0.512002      0.516667
cvx_nn_32               0.926  0.505737      0.511325
cvx-trainable_nn_32     0.934  0.540001      0.531206

In [5]:
df = pd.read_csv('results__school_mini.csv', index_col=0)
df

                          mae         mse
model
ind_nn_8             8.452244  117.456168
common_nn_8          8.345137  111.700328
cvx_nn_8             7.896344  104.010459
cvx-trainable_nn_8   8.264912  114.947976
ind_nn_16            8.087114  106.009070
common_nn_16         8.122348  109.321560
cvx_nn_16            8.192136  108.502559
cvx-trainable_nn_16  8.266314  114.507128
ind_nn_32            8.045062  110.126253
common_nn_32         8.126895  109.476304
cvx_nn_32            8.187554  107.011711
cvx-trainable_nn_32  8.001775  106.252858